export const navBarWidth = 70
export const splitViewWidth = 500
export const splitViewBreakpoint = 1250
export const noCategoryTitle = 'No category'
export const headerWithToolsBreakpoint = 625
export const headerHeightRegular = 50
export const headerHeightWithTools = 80
export const headerHeightWithToolsDoubleLine = 110
export const narrowHeaderBreakpoint = 625
