export const NAV_BAR_WIDTH = 70
export const SPLIT_VIEW_WIDTH = 500
export const SPLIT_VIEW_BREAKPOINT = 1250
export const NO_CATEGORY_TITLE = 'No category'
export const HEADER_HEIGHT_WITH_TOOLS = 75

export const MIN_PANEL_WIDTH = 300
export const MAX_PANEL_WIDTH = 3000
export const APP_MIN_WIDTH = 625
export const APP_MIN_HEIGHT = 650
export const NARROW_MEDIUM_BREAKPOINT = NAV_BAR_WIDTH + 2 * MIN_PANEL_WIDTH
export const MEDIUM_LARGE_BREAKPOINT = NARROW_MEDIUM_BREAKPOINT + MIN_PANEL_WIDTH
export const SCROLL_BAR_WIDTH = 5
export const MAX_ALLOWED_PANELS_COUNT = 3
export const MULTI_COLUMN_BREAKPOINT = 850
export const MULTI_COLUMN_MIN_WIDTH = 550
